package Java201.Exceptions;

import java.util.InputMismatchException;
import java.util.Scanner;

public class Main {

	public static void main(String[] args) {
		//Syntax Hatası -> derleme zamaanı
		//Runtime -> Çalışma esnasında alınan hatalardır
		
		/*
		 * Errorlar JVM ile alakalı müdahale edilemez
		 */
		
		//
		/*
		 * try-catch-finally ile hata yönetimi yaparız
		 * try-> hata olabilecek kod bloğu
		 * catch-> hatayı yakalayan
		 * finally-> hata olsa da olmasa da ne yapılacağını söyleyen blok
		 */
		Scanner scanner = new Scanner(System.in);
		int x = scanner.nextInt();
		int y = scanner.nextInt();
		try {
			System.out.println(x/y);
		}catch(ArithmeticException e) {
			System.out.println("Hata = "+ e);
		}catch (InputMismatchException e) {
			System.out.println("Hata = "+e);
		}finally {
			scanner.close();
		}

	}

}
